path:
  data_dir: js-fakes/midi/*.mid
  test_dir: js-fakes/jsf-extended/*.mid
  model_dir: models/
  out_dir: outputs/
params:
  bpm: 120
  batch_size: 64
  epochs: 500
  layers: 2
  unit: 512
  dropout: 0.2
  embed_size: 256
  sequence_length: 16
  stateful: False
  track_size: 4
output:
  wandb: True
  length: 50
