path:
  data_dir: /home/stu00608/Repositories/js-fakes/midi/*.mid
  model_dir: models/
  out_dir: outputs/
params:
  data_size: 10
  vocab_size: 100
  batch_size: 16
  epochs: 20
  intensity: 90
  resolution: 24
  tracks: 4
  bpm: 120
output:
  length: 20
