path:
  data_dir: /home/stu00608/Repositories/js-fakes/midi/*.mid
  model_dir: models/
  out_dir: outputs/
params:
  data_size: 1
  vocab_size: 100
  batch_size: 64
  epochs: 1000
  intensity: 90
  resolution: 24
  tracks: 4
  bpm: 120
output:
  wandb: True
  length: 20
