path:
  data_dir: /home/stu00608/Repositories/js-fakes/midi/*.mid
  model_dir: models/
  out_dir: outputs/
params:
  data_size: 10
  vocab_size: 200
  batch_size: 64
  epochs: 50
  intensity: 90
  resolution: 24
  tracks: 4
  bpm: 120
output:
  length: 20